// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP91cqX82ZB4moIH_GvNQvUzlEY72OhvU',
    appId: '1:962777516016:web:3db1b63530114e6f62bf35',
    messagingSenderId: '962777516016',
    projectId: 'flutter-chat-app-eac2a',
    authDomain: 'flutter-chat-app-eac2a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-eac2a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl56HvwnHuVGR_ype3nqgts4FK_cwyDwo',
    appId: '1:962777516016:android:0a0498212b90f5ac62bf35',
    messagingSenderId: '962777516016',
    projectId: 'flutter-chat-app-eac2a',
    storageBucket: 'flutter-chat-app-eac2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4EFKuczuZ3JMcnAVHQ-h7J1XwpTxfMqg',
    appId: '1:962777516016:ios:ccb68e9037ba8d1862bf35',
    messagingSenderId: '962777516016',
    projectId: 'flutter-chat-app-eac2a',
    storageBucket: 'flutter-chat-app-eac2a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4EFKuczuZ3JMcnAVHQ-h7J1XwpTxfMqg',
    appId: '1:962777516016:ios:ccb68e9037ba8d1862bf35',
    messagingSenderId: '962777516016',
    projectId: 'flutter-chat-app-eac2a',
    storageBucket: 'flutter-chat-app-eac2a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP91cqX82ZB4moIH_GvNQvUzlEY72OhvU',
    appId: '1:962777516016:web:dac8c7c42ea2c37d62bf35',
    messagingSenderId: '962777516016',
    projectId: 'flutter-chat-app-eac2a',
    authDomain: 'flutter-chat-app-eac2a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-eac2a.firebasestorage.app',
  );

}